### PR TITLE
Window Data Folder Fix

### LINKED ISSUE #115: Windows xdg error when launching debugging session
Problem reported when trying to launch a debugging session.

> I'm getting the following error message:
>
>        ENOENT: no such file or directory, mkdir
>        'C:\Users\xxxxxxx\AppData\Roaming\xdg.data\dapodil'
>
> Under Roaming, I do not have an xdg.data folder.

### PR DESCRIPTION
**Pull request by Shanedell**
- Make sure the xdg.data folder is created on windows

Fixes #115

### CODE REVIEW

**Comment by jw3** [comment]
Tested this in v0.0.15-pre1 on a windows 10 machine that never had VSCode installed I still get the same error as reported.

**Review by jw3 — CHANGES_REQUESTED** [review]
Tested this in v0.0.15-pre1 on a windows 10 machine that never had VSCode installed I still get the same error as reported.

File: src/daffodilDebugger.ts [hunk 1]
```diff
@@ -80,8 +80,14 @@ export async function getDebugger(config: vscode.DebugConfiguration) {
 
     if (vscode.workspace.workspaceFolders !== undefined) {
       let rootPath = xdgAppPaths.data()
+      let xdgDataFolderArray = xdgAppPaths.data().split('/')
+      xdgDataFolderArray.pop()
+      let xdgDataFolderString = xdgDataFolderArray.join('/')
 
-      // If directory for storing debugger does exist create it
+      // If data and app directories for storing debugger does exist create them
```
Comment (jw3) [inline src/daffodilDebugger.ts:87]: does "not" exist?

File: src/daffodilDebugger.ts [hunk 2]
```diff
@@ -80,8 +80,14 @@ export async function getDebugger(config: vscode.DebugConfiguration) {
...
+      if (!fs.existsSync(xdgDataFolderString)) {
+        fs.mkdirSync(xdgDataFolderString)
+      }
       if (!fs.existsSync(rootPath)) {
         fs.mkdirSync(rootPath)
```
Comment (jw3) [inline src/daffodilDebugger.ts:92]: If this is to recurse you can do `fs.mkdir(path, {recursive: true})`, by default it does not.

Did you need that new logic, or just need to recurse here?

File: src/daffodilDebugger.ts [hunk 3]
```diff
@@ -80,8 +80,14 @@ export async function getDebugger(config: vscode.DebugConfiguration) {
 
     if (vscode.workspace.workspaceFolders !== undefined) {
       let rootPath = xdgAppPaths.data()
+      let xdgDataFolderArray = xdgAppPaths.data().split('/')
```
Comment (jw3) [inline src/daffodilDebugger.ts:83]: Is this needed if you recurse?

**Comment by jw3** [comment]
Pushed a commit to fix a stray bracket and tested everything against 15-pre3 :rocket: 

But it did spawn another issue after launch #119
