### PR TITLE
Consolidate empty program and data checking.

### LINKED ISSUE #111: Debug session doesn't connect to launched backend
Fresh install of 0.0.14:

- Open `jpeg.dfdl.xsd` in VSCode, choose menu "Daffodil Debug: Debug File".
- Backend launches waiting for connection from extension. Nothing connects, backend exits after 10 seconds.

Will try to reproduce locally at the HEAD of the main branch.

### LINKED ISSUE #113: Canceling schema or data dialogs still launches backend, which then exits with error
(Version 0.0.14)

If you cancel either the schema or data dialogs, the backend is still launched (and then exits with an error after the 10 second timeout).

### PR DESCRIPTION
**Pull request by arosien**
Fixes #111, fixes #113.

### CODE REVIEW

**Review by Shanedell — APPROVED** [review]

File: src/activateDaffodilDebug.ts [hunk 1]
```diff
@@ -160,20 +122,9 @@ export function activateDaffodilDebug(
...
-        ).toString('utf8')
-        if (programFile === '') {
-          stopDebugging()
-          return ''
-        }
-
+      async (_) => {
         // Open native file explorer to allow user to select data file from anywhere on their machine
-        let dataFile = await vscode.window
+        return await vscode.window
```
Comment (jw3) [inline src/activateDaffodilDebug.ts:127]: wonder why the linter doesnt catch the redundant await here?
